language: c++
compiler:
  - gcc
  - clang
addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - nasm
      - gcc-multilib
      - gcc-4.8
      - g++-4.8
      - clang
script: scons check
notifications:
  email:
    recipients:
      - matt.fichman@gmail.com
    on_success: always # never change
    on_failure: always # never change
 
sudo: false
