language: c++
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - nasm
      - gcc-multilib
      - gcc-4.8
      - g++-4.8
      - clang
script: scons
notifications:
  email:
    recipients:
      - matt.fichman@gmail.com
    on_success: change #always # never change
    on_failure: change #always # never change
 
sudo: false
